name: Run ELT + dbt

on:
  schedule:
    - cron: "0 12-22/2 * * *"
  workflow_dispatch:

env:
  PG_SCHEMA: ${{ secrets.PG_SCHEMA }}
  PG_DSN: ${{ secrets.PG_DSN }}

jobs:
  run-elt:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/all.txt

      - name: Run ingestion
        env:
          CR_API_USER: ${{ secrets.CR_API_USER }}
          CR_API_PW: ${{ secrets.CR_API_PW }}
          PODPLAY_API_KEY: ${{ secrets.PODPLAY_API_KEY }}
        run: |
          python3 -m ingestion.main all

  run-dbt:
    environment: prod
    runs-on: ubuntu-latest
    needs: run-elt
    steps:
      - uses: actions/checkout@v4

      - name: Install dbt
        run: pip install dbt-postgres

      - name: Install dbt packages
        run: |
          cd dbt_pklyn
          dbt deps

      - name: Run dbt models
        run: |
          cd dbt_pklyn
          dbt run \
            --project-dir ${{ github.workspace }}/dbt_pklyn \
            --target prod \
            --exclude tag:skip
